import { useState } from 'react'
const initialForm={nombre:'',email:'',telefono:'',destino:'',tipoViaje:'',comentarios:'',novedades:false}
export default function Contact(){
 const [form,setForm]=useState(initialForm)
 const handleChange=(e)=>{const {name,value,type,checked}=e.target; const newValue=type==='checkbox'?checked:value; console.log('Evento de input:',name,newValue); setForm(prev=>({...prev,[name]:newValue}))}
 const handleSubmit=(e)=>{e.preventDefault(); console.log('Datos enviados:',form); alert('¡Consulta enviada! Revisá la consola para ver los datos.')}
 const handleReset=()=>{setForm(initialForm); console.log('Formulario reiniciado')}
 return <section className="section contact-section" id="contacto"><div className="container contact-layout"><div className="contact-copy"><p className="eyebrow">Diseñemos tu próxima aventura</p><h2>Contanos cómo querés viajar</h2><p>Completá el formulario y un asesor se pondrá en contacto para preparar una propuesta a tu medida.</p><div className="contact-points"><div><span><strong>Email</strong> hola@rumbosur.com</span></div><div><span><strong>WhatsApp</strong> +54 9 11 5555-2026</span></div></div></div><form className="contact-form" onSubmit={handleSubmit} onReset={handleReset}><div className="form-row"><div className="field"><label htmlFor="nombre">Nombre y apellido</label><input type="text" id="nombre" name="nombre" placeholder="Ej.: Micaela Pavone" required value={form.nombre} onChange={handleChange}/></div><div className="field"><label htmlFor="email">Email</label><input type="email" id="email" name="email" placeholder="nombre@email.com" required value={form.email} onChange={handleChange}/></div></div><div className="form-row"><div className="field"><label htmlFor="telefono">Teléfono</label><input type="tel" id="telefono" name="telefono" placeholder="11 5555 5555" required value={form.telefono} onChange={handleChange}/></div><div className="field"><label htmlFor="destino">Destino de interés</label><select id="destino" name="destino" required value={form.destino} onChange={handleChange}><option value="">Seleccionar</option><option>Patagonia</option><option>Cataratas del Iguazú</option><option>Río de Janeiro</option><option>Otro destino</option></select></div></div><fieldset className="field choice-group"><legend>Tipo de viaje</legend>{[['pareja','En pareja'],['familia','En familia'],['amigos','Con amigos']].map(([v,l])=><label key={v}><input type="radio" name="tipoViaje" value={v} required={v==='pareja'} checked={form.tipoViaje===v} onChange={handleChange}/> {l}</label>)}</fieldset><div className="field"><label htmlFor="comentarios">Comentarios</label><textarea id="comentarios" name="comentarios" rows="5" placeholder="Contanos fechas aproximadas, cantidad de personas y cualquier preferencia especial." value={form.comentarios} onChange={handleChange}/></div><label className="checkbox"><input type="checkbox" name="novedades" checked={form.novedades} onChange={handleChange}/> Quiero recibir promociones y novedades.</label><div className="form-actions"><button className="button button-primary" type="submit">Enviar consulta</button><button className="button button-reset" type="reset">Limpiar</button></div></form></div></section>
}
